// TYT / AYT ders ve konu başlıkları — kaynak: DERS PLANLAMA.xlsx (DATA sayfası)
// Sınav analiz modülünün temel verisi: konu bazlı analiz bu listelere dayanacak.
// Geometri konuları TYT ve AYT matematiğinde ortak olduğu için tek liste paylaşılır.

export const EXAM_TOPICS = {
  TYT: {
    "Türkçe": [
      "Sözcükte Anlam",
      "Söz Yorumu",
      "Deyim ve Atasözü",
      "Cümlede Anlam",
      "Paragraf",
      "Paragrafta Anlatım Teknikleri",
      "Paragrafta Düşünceyi Geliştirme Yolları",
      "Paragrafta Yapı",
      "Paragrafta Konu-Ana Düşünce",
      "Paragrafta Yardımcı Düşünce",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı/Ekler",
      "Sözcük Türleri",
      "İsimler",
      "Zamirler",
      "Sıfatlar",
      "Zarflar",
      "Edat – Bağlaç – Ünlem",
      "Fiiller",
      "Fiilde Anlam (Kip-Kişi-Yapı)",
      "Ek Fiil",
      "Fiilimsi",
      "Fiilde Çatı",
      "Sözcük Grupları",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
    ],
    "Matematik": [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB – EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "Sayı Problemleri",
      "Kesir Problemleri",
      "Yaş Problemleri",
      "Hareket Hız Problemleri",
      "İşçi Emek Problemleri",
      "Yüzde Problemleri",
      "Kar Zarar Problemleri",
      "Karışım Problemleri",
      "Grafik Problemleri",
      "Rutin Olmayan Problemleri",
      "Kümeler – Kartezyen Çarpım",
      "Mantık",
      "Fonskiyonlar",
      "Polinomlar",
      "2.Dereceden Denklemler",
      "Permütasyon ve Kombinasyon",
      "Olasılık",
      "Veri – İstatistik",
    ],
    "Geometri": [
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Özel Üçgenler",
      "Dik Üçgen",
      "İkizkenar Üçgen",
      "Eşkenar Üçgen",
      "Açıortay",
      "Kenarortay",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açı Kenar Bağıntıları",
      "Çokgenler",
      "Özel Dörtgenler",
      "Dörtgenler",
      "Deltoid",
      "Paralelkenar",
      "Eşkenar Dörtgen",
      "Dikdörtgen",
      "Kare",
      "Yamuk",
      "Çember ve Daire",
      "Çemberde Açı",
      "Çemberde Uzun",
      "Dairede Çevre ve Alan",
      "Analitik Geometri",
      "Noktanın Analitiği",
      "Doğrunun Analitiği",
      "Dönüşüm Geometrisi",
      "Katı Cisimler",
      "Çemberin Analitiği",
    ],
    "Fizik": [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Sıvıların Kaldırma Kuvveti",
      "Basınç",
      "Isı, Sıcaklık ve Genleşme",
      "Hareket ve Kuvvet",
      "Dinamik",
      "İş, Güç ve Enerji",
      "Elektrik",
      "Manyetizma",
      "Dalgalar",
      "Optik",
    ],
    "Kimya": [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Doğa ve Kimya",
      "Kimyanın Temel Kanunları",
      "Kimyasal Hesaplamalar",
      "Karışımlar",
      "Asit, Baz ve Tuz",
      "Kimya Her Yerde",
    ],
    "Biyoloji": [
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Organelleri",
      "Hücre Zarından Madde Geçişi",
      "Canlıların Sınıflandırılması",
      "Mitoz ve Eşeysiz Üreme",
      "Mayoz ve Eşeyli Üreme",
      "Kalıtım",
      "Ekosistem Ekolojisi",
      "Güncel Çevre Sorunları",
    ],
    "Tarih": [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ’da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti",
      "Devletleşme Sürecinde Savaşçılar ve Askerler",
      "Beylikten Devlete Osmanlı Medeniyeti",
      "Dünya Gücü Osmanlı",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Klasik Çağda Osmanlı Toplum Düzeni",
      "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
      "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
      "Sermaye ve Emek",
      "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
      "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Milli Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
    ],
    "Coğrafya": [
      "Doğa ve İnsan",
      "Dünya’nın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "Harita Bilgisi",
      "Atmosfer ve Sıcaklık",
      "İklimler",
      "Basınç ve Rüzgarlar",
      "Nem, Yağış ve Buharlaşma",
      "İç Kuvvetler / Dış Kuvvetler",
      "Su – Toprak ve Bitkiler",
      "Nüfus",
      "Göç",
      "Yerleşme",
      "Türkiye’nin Yer Şekilleri",
      "Ekonomik Faaliyetler",
      "Bölgeler",
      "Uluslararası Ulaşım Hatları",
      "Çevre ve Toplum",
      "Doğal Afetler",
    ],
    "Felsefe": [
      "Felsefe’nin Konusu",
      "Bilgi Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Bilim Felsefesi",
      "İlk Çağ Felsefesi",
      "2. Yüzyıl ve 15. Yüzyıl Felsefeleri",
      "15. Yüzyıl ve 17. Yüzyıl Felsefeleri",
      "18. Yüzyıl ve 19. Yüzyıl Felsefeleri",
      "20. Yüzyıl Felsefesi",
    ],
    "Din Kültürü": [
      "Bilgi ve İnanç",
      "İslam ve İbadet",
      "Ahlak ve Değerler",
      "Allah İnsan İlişkisi",
      "Hz. Muhammed (S.A.V.)",
      "Vahiy ve Akıl",
      "İslam Düşüncesinde Yorumlar, Mezhepler",
      "Din, Kültür ve Medeniyet",
      "İslam ve Bilim, Estetik, Barış",
      "Yaşayan Dinler",
    ],
  },
  AYT: {
    "Matematik": [
      "Fonksiyonlar",
      "2.Dereceden Denklemler",
      "Mantık",
      "Parabol",
      "Trigonometri",
      "Karmaşık sayılar",
      "Polinomlar",
      "Logoritma",
      "Denklem çözme",
      "Diziler",
      "Permütasyon-Kombinasyon-Olasılık – Binom",
      "Limit",
      "Türev",
      "İntegral",
      "Vektörler",
      "Kümeler ve Kartezyen Çarpım",
    ],
    "Geometri": [
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Özel Üçgenler",
      "Dik Üçgen",
      "İkizkenar Üçgen",
      "Eşkenar Üçgen",
      "Açıortay",
      "Kenarortay",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açı Kenar Bağıntıları",
      "Çokgenler",
      "Özel Dörtgenler",
      "Dörtgenler",
      "Deltoid",
      "Paralelkenar",
      "Eşkenar Dörtgen",
      "Dikdörtgen",
      "Kare",
      "Yamuk",
      "Çember ve Daire",
      "Çemberde Açı",
      "Çemberde Uzun",
      "Dairede Çevre ve Alan",
      "Analitik Geometri",
      "Noktanın Analitiği",
      "Doğrunun Analitiği",
      "Dönüşüm Geometrisi",
      "Katı Cisimler",
      "Çemberin Analitiği",
    ],
    "Fizik": [
      "Vektörler",
      "Hareket",
      "Newton’un Hareket Yasaları",
      "Bir Boyutta Savit İvmeli Hareket",
      "Atışlar",
      "İş, Güç ve Enerji II",
      "İtme ve Momentum",
      "Kuvvet, Tork ve Denge",
      "Kütle Merkezi",
      "Basit Makineler",
      "Elektrik Alan ve Potansiyel",
      "Paralel Levhalar ve Sığa",
      "Manyetik Alan ve Manyetik Kuvvet",
      "İndüksiyon, Alternatif Akım ve Transformatörler",
      "Çembersel Hareket",
      "Dönme, Yuvarlanma ve Açısal Momentum",
      "Kütle Çekim ve Kepler Yasaları",
      "Basit Harmonik Hareket",
      "Dalga Mekaniği ve Elektromanyetik Dalgalar",
      "Atom Fiziğine Giriş ve Radyoaktivite",
      "Fotoelektrik Olay ve Compton Olayı",
      "Modern Fiziğin Teknolojideki Uygulamaları",
      "Özel Görelillik",
    ],
    "Kimya": [
      "Modern Atom Teorisi",
      "Gazlar",
      "Çözeltiler",
      "Kimyasal Tepkimelerde Enerji",
      "Kimyasal Tepkimelerde Hız",
      "Kimyasal Tepkimelerde Denge",
      "Asit-Baz Dengesi",
      "Çözünürlük Dengesi",
      "Kimya ve Elektrik",
      "Organik Kimya",
    ],
    "Biyoloji": [
      "Sinir Sistemi",
      "Endokrin Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım ve Bağışıklık Sistemi",
      "Solunum Sistemi",
      "Boşaltım Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Komünite ve Popülasyon Ekolojisi",
      "Nükleik Asitler",
      "Genetik Şifre ve Protein Sentezi",
      "Canlılık ve Enerji",
      "Fotosentez ve Kemosentez",
      "Hücresel Solunum",
      "Bitki Biyolojisi",
      "Canlılar ve Çevre",
    ],
    "Edebiyat": [
      "Anlam Bilgisi",
      "Şiir Bilgisi",
      "Edebi Sanatlar",
      "Edebi Metinler (Düzyazı)",
      "Tiyatro",
      "İslamiyet Öncesi ve Geçiş Dönemi Türk Edebiyatı",
      "Halk Edebiyatı",
      "Divan Edebiyatı",
      "Edebi Akımlar",
      "Tanzimat Edebiyatı",
      "Servetifünun ve Fecriati Edebiyatı",
      "Millî Edebiyat",
      "Cumhuriyet Dönemi Türk Edebiyatı",
    ],
    "Tarih": [
      "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
      "II. Dünya Savaşı Sürecinde – Sonrasında Türkiye ve Dünya",
      "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya",
    ],
    "Coğrafya": [
      "İklim ve Yer Şekilleri",
      "Coğrafi Konum",
      "Dünya’nın Şekli ve Hareketleri",
      "Harita Bilgisi",
      "İç ve Dış Kuvvetler",
      "Ekosistem",
      "Nüfus Politikaları",
      "Türkiye’de Nüfus ve Yerleşme",
      "Ekonomik Faaliyetler ve Doğal Kaynaklar",
      "Göç ve Şehirleşme",
      "Türkiye Ekonomisi",
      "Türkiye’nin İşlevsel Bölgeleri ve Kalkınma Projeleri",
      "Küresel Ticaret",
      "Kültür Bölgeleri",
      "Küresel ve Bölgesel Örgütler",
      "Ülkeler Arası Etkileşimler",
      "Bölgeler ve Ülkeler",
      "Çevre ve Toplum",
    ],
  },
};

// Bir sınav türünün ders listesi (ör. konu seçtirme dropdown'ları için)
export const examSubjectsOf = (examType) => Object.keys(EXAM_TOPICS[examType] ?? {});

// Bir dersin konu listesi
export const topicsOf = (examType, subject) => EXAM_TOPICS[examType]?.[subject] ?? [];
